"""
PreviewController.
Handles business logic for the PreviewPanel, separating concerns from UI rendering.
"""
from __future__ import annotations
import base64
import html
import os
import re
from PyQt6 import QtCore, QtWidgets, QtWebChannel
from PyQt6.QtCore import pyqtSlot, pyqtSignal, QObject

from core.logger import logger
from ui.styles import Theme
from services.ocr.latex_to_mathml import LatexToMathML
from latex2mathml.converter import convert as latex2mathml_convert

class JSBridge(QObject):
    """Bridge for communication between Python and JavaScript."""
    latexChanged = pyqtSignal(str)
    mathmlGenerated = pyqtSignal(str)

    @pyqtSlot(str)
    def updateLatex(self, latex):
        """Receive updated LaTeX from MathLive."""
        self.latexChanged.emit(latex)
        
    @pyqtSlot(str)
    def updateMathML(self, mathml):
        """Receive generated MathML from MathJax."""
        self.mathmlGenerated.emit(mathml)

class PreviewController(QObject):
    """
    Controller for PreviewPanel.
    Manages state, handles user interactions, and prepares data for display.
    """
    # Signals to update View
    update_html = pyqtSignal(str)
    update_mathml_source = pyqtSignal(str)
    update_status = pyqtSignal(bool, float) # is_valid, confidence
    snip_saved = pyqtSignal(object) # snip data dict
    export_requested = pyqtSignal(str)

    def __init__(self, view=None):
        super().__init__()
        self._view = view # Weak ref or direct ref
        self._stored_latex = ""
        self._current_mathml = ""
        self._current_image_path = None
        self._is_visual_editor_active = False
        self.bridge = JSBridge()
        self.bridge.mathmlGenerated.connect(self._handle_mathml_from_js)
        
        # Services
        self.latex_converter = LatexToMathML()
        
    def _handle_mathml_from_js(self, mathml: str):
        """Handle MathML generated by client-side MathJax."""
        if mathml and mathml != self._current_mathml:
            logger.info(f"[PreviewController] Received MathML from MathJax ({len(mathml)} chars)")
            self._current_mathml = mathml
            self.update_mathml_source.emit(mathml)

    def set_visual_editor_mode(self, active: bool):
        """Toggle visual editor mode."""
        self._is_visual_editor_active = active
        if active:
            self._render_mathlive()
        else:
            # Re-render standard preview
            self._render_standard_view()

    def handle_visual_editor_change(self, latex: str):
        """Handle updates from Visual Editor."""
        clean_latex = latex.strip()
        self._stored_latex = clean_latex
        
        try:
            # We use the raw converter here for speed/consistency in the edit loop
            # Or use our pipeline if needed. Pipeline is safer.
            # But carefully avoiding infinite loop or full re-render
            mathml = latex2mathml_convert(clean_latex) 
            self._current_mathml = mathml
            self.update_mathml_source.emit(mathml)
        except Exception as e:
            logger.warning(f"Visual Editor conversion failed: {e}")

    def update_content(self, latex: str, mathml: str, is_valid: bool, confidence: float, image_path: str = None, ast_data: dict = None):
        """Main update entry point."""
        logger.info(f"[PreviewController] update_content called - LaTeX: {len(latex) if latex else 0} chars")
        
        self._stored_latex = latex
        # MathML might be empty or invalid from OCR, but we don't care about it for preview anymore.
        # We might still want it for the "Copy MathML" feature, so we keep storing it if provided.
        self._current_mathml = mathml 
        self._current_image_path = image_path
        self._current_ast_data = ast_data
        
        # Emit MathML source update for the text box (optional, might want to generate from MathJax later)
        if mathml:
            self.update_mathml_source.emit(mathml)
        
        # Emit status update for UI visibility (indicator, confidence, refining label)
        self.update_status.emit(is_valid, confidence)
        
        # Reset mode if new image
        if not self._is_visual_editor_active:
             logger.info(f"[PreviewController] Rendering standard view (MathJax)")
             self._render_standard_view()
        else:
             logger.info(f"[PreviewController] Rendering MathLive")
             self._render_mathlive()

    def _render_standard_view(self):
        """Generate HTML for standard read-only view."""
        # Use stored LaTeX as source of truth, but prefer MathML for rendering if available
        latex_src = self._stored_latex
        mathml_src = self._current_mathml
        
        logger.info(f"[PreviewController] _render_standard_view - LaTeX: {len(latex_src) if latex_src else 0} chars, MML: {len(mathml_src) if mathml_src else 0} chars")
        html_content = self._build_standard_html(latex_src, mathml_src)
        self.update_html.emit(html_content)

    def _render_mathlive(self):
        """Generate HTML for visual editor."""
        qwebchannel_url = "qrc:///qtwebchannel/qwebchannel.js"
        latex_b64 = base64.b64encode(self._stored_latex.encode('utf-8')).decode('utf-8')
        
        html_code = f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <script src="{qwebchannel_url}"></script>
            <script src="//unpkg.com/mathlive"></script>
            <style>
                body {{
                    background-color: {Theme.SURFACE};
                    color: {Theme.TEXT_PRIMARY};
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    height: 100vh;
                    margin: 0;
                    font-family: system-ui;
                }}
                math-field {{
                    font-size: 24px;
                    padding: 8px;
                    border-radius: 8px;
                    border: 1px solid {Theme.BORDER};
                    background: {Theme.BACKGROUND};
                    color: {Theme.TEXT_PRIMARY};
                    width: 90%;
                    max-width: 800px;
                }}
                math-field::part(content) {{
                    color: {Theme.TEXT_PRIMARY};
                }}
            </style>
        </head>
        <body>
            <math-field id="mf" virtual-keyboard-mode="manual"></math-field>
            <script>
                new QWebChannel(qt.webChannelTransport, function(channel) {{
                    window.bridge = channel.objects.bridge;
                    const mf = document.getElementById('mf');
                    try {{
                        const content = atob("{latex_b64}");
                        const decoded = new TextDecoder().decode(Uint8Array.from(content, c => c.charCodeAt(0)));
                        mf.setValue(decoded);
                    }} catch(e) {{ console.error(e); }}
                    mf.addEventListener('input', (ev) => {{
                        if (window.bridge) window.bridge.updateLatex(mf.getValue());
                    }});
                }});
            </script>
        </body>
        </html>
        """
        self.update_html.emit(html_code)

    def _build_standard_html(self, latex: str, mathml: str = None) -> str:
        """Construct standard view HTML using MathJax (prefers MathML)."""
        if not latex and not mathml:
            return ""

        import html
        qwebchannel_url = "qrc:///qtwebchannel/qwebchannel.js"
        
        from utils.resource_utils import get_resource_path, get_mathjax_path
        
        mathjax_url = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js"
        local_mj = get_mathjax_path()
        if os.path.exists(local_mj):
            mathjax_url = QtCore.QUrl.fromLocalFile(local_mj).toString()
            logger.info(f"[PreviewController] Found local MathJax: {local_mj}")
        else:
            logger.warning(f"[PreviewController] Local MathJax not found at {local_mj}, using CDN")

        # If we have MathML, we wrap it in a div. MathJax will process it.
        # If not, we use LaTeX.
        if mathml and "<math" in mathml:
            display_content = mathml
        else:
            escaped_latex = html.escape(latex)
            display_content = f"\\[{escaped_latex}\\]"

        return f"""
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Fira+Code&display=swap" rel="stylesheet">
            <script src="{qwebchannel_url}"></script>
            <script>
            window.MathJax = {{
              tex: {{
                inlineMath: [['$', '$'], ['\\\\(', '\\\\)']],
                displayMath: [['$$', '$$'], ['\\\\[', '\\\\]']],
                processEscapes: true,
                packages: {{'[+]': ['base', 'ams', 'noundefined', 'amsmath']}},
                tags: 'ams'
              }},
              svg: {{
                  fontCache: 'none',
                  scale: 1.1,
                  displayAlign: 'center',
                  displayIndent: '0'
              }},
              options: {{
                enableMenu: false,
                menuOptions: {{
                    settings: {{
                        assistiveMml: false,
                        collapsible: false
                    }}
                }}
              }},
              startup: {{
                typeset: true,
                ready: () => {{
                  MathJax.startup.defaultReady();
                }},
                pageReady: () => {{
                  return MathJax.startup.defaultPageReady().then(() => {{
                    extractMathML();
                  }});
                }}
              }}
            }};

            function extractMathML() {{
                try {{
                    const m = window.MathJax;
                    if (!m || !m.startup || !m.startup.document) return;
                    
                    const items = m.startup.document.math;
                    if (items && items.length > 0) {{
                        const mml = items[0].root.toMML();
                        if (window.bridge) window.bridge.updateMathML(mml);
                    }}
                }} catch (e) {{
                    console.error("MML Extraction Error:", e);
                }}
            }}

            if (typeof qt !== 'undefined') {{
                new QWebChannel(qt.webChannelTransport, function (channel) {{
                    window.bridge = channel.objects.bridge;
                    extractMathML();
                }});
            }}
            </script>
            <script id="MathJax-script" src="{mathjax_url}" onerror="console.error('Script failed to load!')"></script>
            <style>
                :root {{
                    --surface: {Theme.SURFACE};
                    --text: {Theme.TEXT_PRIMARY};
                    --text-secondary: {Theme.TEXT_SECONDARY if hasattr(Theme, 'TEXT_SECONDARY') else '#94a3b8'};
                    --border: {Theme.BORDER};
                    --accent: #3b82f6;
                }}

                * {{
                    box-sizing: border-box;
                    -webkit-font-smoothing: antialiased;
                }}

                body {{
                    background-color: var(--surface);
                    color: var(--text);
                    font-family: 'Inter', -apple-system, system-ui, sans-serif;
                    margin: 0;
                    padding: 0;
                    display: flex;
                    flex-direction: column;
                    width: 100%;
                    min-height: 100vh;
                    overflow: auto;
                    background-image: 
                        radial-gradient(circle at 0% 0%, rgba(59, 130, 246, 0.02) 0%, transparent 40%),
                        radial-gradient(circle at 100% 100%, rgba(59, 130, 246, 0.02) 0%, transparent 40%);
                }}
                
                .math-viewport {{
                    flex: 1;
                    display: flex;
                    flex-direction: column;
                    justify-content: center;
                    align-items: center;
                    padding: 24px; /* Reduced padding */
                    width: 100%;
                    min-height: 100%;
                }}

                .math-content {{
                    width: 100%;
                    max-width: 100%;
                    font-size: 2.0em; /* Reduced from 2.2em per request */
                    display: flex;
                    justify-content: center;
                    outline: none;
                }}

                /* Remove default MathJax margins that cause displacement */
                mjx-container {{
                    margin: 0 !important;
                    display: inline-block !important; /* Allow centering via flex parent */
                    text-align: center;
                }}

                /* Premium Scrollbar for the whole page */
                ::-webkit-scrollbar {{
                    width: 8px;
                    height: 8px;
                }}
                ::-webkit-scrollbar-track {{
                    background: transparent;
                }}
                ::-webkit-scrollbar-thumb {{
                    background: var(--border);
                    border-radius: 10px;
                }}
                ::-webkit-scrollbar-thumb:hover {{
                    background: var(--accent);
                }}

                /* Table/Matrix Spacing for clarity */
                mjx-table {{
                    border-collapse: separate;
                    border-spacing: 0.6em 1.4em !important;
                }}
                
                mjx-mtr {{
                    padding: 1em 0;
                }}
            </style>
        </head>
        <body>
            <div class="math-viewport">
                <div class="math-content" id="math-display">
                    {display_content}
                </div>
            </div>
        </body>
        </html>
        """




    def save_current_snip(self):
        """Prepare snip data for saving."""
        if not self._stored_latex:
            return
            
        data = {
            "latex": self._stored_latex,
            "mathml": self._current_mathml,
            "image_path": self._current_image_path
        }
        self.snip_saved.emit(data)
