"""
Word Exporter for MathML.
Generates Word-compatible HTML files that preserve MathML equations.
"""

from pathlib import Path
from core.config import settings
from core.logger import logger

class WordExporter:
    """Exports content to MS Word compatible formats."""
    
    def __init__(self):
        self.output_dir = settings.data_dir / "exports"
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def export_to_word(self, mathml: str, filepath: str | Path = None) -> Path:
        """
        Export MathML to a Word-compatible HTML file.
        Word 2013+ automatically converts MathML to Order Math (OMML) when opening.
        """
        if not mathml:
            raise ValueError("No MathML content to export")
            
        import datetime
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        
        if filepath:
            path = Path(filepath)
        else:
            filename = f"math_export_{timestamp}.doc"
            path = self.output_dir / filename
        
        # Ensure parent exists
        path.parent.mkdir(parents=True, exist_ok=True)
        
        # Construct Word-Compatible HTML
        # We use the specific XML namespaces that help Word recognize content
        html_content = f"""
        <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head>
            <meta charset="utf-8">
            <title>Mathpix Clone Export</title>
            <style>
                body {{ font-family: 'Times New Roman', serif; font-size: 12pt; }}
            </style>
            <!--[if gte mso 9]>
            <xml>
            <w:WordDocument>
                <w:View>Print</w:View>
                <w:Zoom>100</w:Zoom>
                <w:DoNotOptimizeForBrowser/>
            </w:WordDocument>
            </xml>
            <![endif]-->
        </head>
        <body>
            <p>Equation Export ({timestamp}):</p>
            <br/>
            {mathml}
            <br/>
            <p><i>Generated by MathML Extractor</i></p>
        </body>
        </html>
        """
        
        try:
            path.write_text(html_content, encoding="utf-8")
            logger.info(f"Exported Word document to {path}")
            return path
        except Exception as e:
            logger.error(f"Failed to export to Word: {e}")
            raise e
