"""AST Visualizer Widget.

This module provides a tree widget to inspect the structure of the 
Abstract Syntax Tree (AST) generated by the OCR pipeline.
"""
from PyQt6.QtWidgets import (
    QWidget, QVBoxLayout, QTreeWidget, QTreeWidgetItem, 
    QLabel, QHeaderView
)
from PyQt6.QtCore import Qt
from services.ocr.ast import ASTNode

class ASTVisualizerPanel(QWidget):
    """A panel to visualize AST structure."""
    
    def __init__(self, parent=None):
        super().__init__(parent)
        self._init_ui()
        
    def _init_ui(self):
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        
        # Header/Description
        self.label = QLabel("Abstract Syntax Tree Structure")
        self.label.setStyleSheet("color: #8b9bb4; font-weight: bold; padding: 5px;")
        layout.addWidget(self.label)
        
        # Tree Widget
        self.tree = QTreeWidget()
        self.tree.setHeaderLabels(["Node Type", "Value", "Children"])
        self.tree.header().setSectionResizeMode(0, QHeaderView.ResizeMode.ResizeToContents)
        self.tree.header().setSectionResizeMode(1, QHeaderView.ResizeMode.Stretch)
        self.tree.header().setSectionResizeMode(2, QHeaderView.ResizeMode.ResizeToContents)
        self.tree.setAlternatingRowColors(True)
        self.tree.setStyleSheet("""
            QTreeWidget {
                background-color: #1a1b26;
                color: #a9b1d6;
                border: 1px solid #414868;
                border-radius: 4px;
            }
            QTreeWidget::item {
                padding: 4px;
            }
            QTreeWidget::item:selected {
                background-color: #3d59a1;
            }
            QHeaderView::section {
                background-color: #24283b;
                color: #c0caf5;
                padding: 4px;
                border: 1px solid #414868;
            }
        """)
        layout.addWidget(self.tree)
        
    def display_ast(self, ast_node: ASTNode):
        """Populate the tree with AST data."""
        self.tree.clear()
        if not ast_node:
            return
            
        root_item = self._add_node(ast_node, self.tree.invisibleRootItem())
        root_item.setExpanded(True)
        
    def _add_node(self, node: ASTNode, parent_item) -> QTreeWidgetItem:
        """Recursively add nodes to the tree."""
        # Create item
        item = QTreeWidgetItem(parent_item)
        
        # Set columns
        item.setText(0, node.node_type)
        item.setText(1, node.value if node.value else "")
        item.setText(2, str(len(node.children)))
        
        # Style based on type
        if node.node_type == "equation":
            item.setForeground(0, Qt.GlobalColor.cyan)
        elif node.node_type in ["fraction", "sqrt", "root", "matrix"]:
            item.setForeground(0, Qt.GlobalColor.yellow)
        elif node.node_type == "symbol":
            item.setForeground(0, Qt.GlobalColor.white)
            if node.value:
                item.setForeground(1, Qt.GlobalColor.green)
        
        # Process children
        for child in node.children:
            self._add_node(child, item)
            
        return item
